Hello my dear students.  Here I am in Colab, starting fresh with a new Notebook.  What would I like to refresh my memory about?  Lets look at pandas Series type object.  

What I discover for myself in this worksheet is that I can feed the pandas DataFrame with a list of Series, in which case their names become rows.  

I might also name the Series inside a dictionary, using name : Series pairs.  In that case, the Series go in as columns, not as rows.

In [1]:
import pandas as pd
from pandas import Series # also allowed
import numpy as np

In [2]:
s1 = pd.Series(1) # is just a scalar OK?

In [3]:
s1

0    1
dtype: int64

In [4]:
s1.name = "Space OK?"

In [5]:
s1

0    1
Name: Space OK?, dtype: int64

In [6]:
s2 = Series(2, index = ["a"], name = "Surprise me!")

In [7]:
s2

a    2
Name: Surprise me!, dtype: int64

Now lets see what effect Series names have on pandas DataFrame column names.

In [8]:
df = pd.DataFrame([s1, s2]) # sequences side by side with no new information

In [9]:
df

                0    a
Space OK?     1.0  NaN
Surprise me!  NaN  2.0

In [10]:
s2

a    2
Name: Surprise me!, dtype: int64

In [11]:
s3 =s2.reset_index([0], drop=True)

In [12]:
s3

0    2
Name: Surprise me!, dtype: int64

In [13]:
s1

0    1
Name: Space OK?, dtype: int64

In [14]:
pd.DataFrame([s1, s3])

              0
Space OK?     1
Surprise me!  2

In [15]:
s4 = pd.Series(np.arange(4), name = "label4")

In [16]:
s4

0    0
1    1
2    2
3    3
Name: label4, dtype: int64

In [17]:
s5 = pd.Series(np.arange(4,8), name = "label5")

In [18]:
s5

0    4
1    5
2    6
3    7
Name: label5, dtype: int64

In [19]:
pd.DataFrame([s4, s5])

        0  1  2  3
label4  0  1  2  3
label5  4  5  6  7

In [20]:
pd.DataFrame({"A":s4, "B":s5})

   A  B
0  0  4
1  1  5
2  2  6
3  3  7